---
title: "Shiny-Enabled Dashboard for NYC Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r}
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(lubridate)
library(forcats)
library(stringr)
library(viridis)
library(ggplot2)
library(dplyr)
library(shiny)
```

```{r}
##load data
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() %>% 
  as.data.frame() %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  separate(grade_date, into = c("grade_date", "takeaway"), sep = "T") %>%
  select(-takeaway) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = as.numeric(month),
         month = as.factor(month)) %>% 
  mutate(cuisine_description = recode(cuisine_description, "Café/Coffee/Tea" = "Cafe", "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin")) %>%
  rename(name = dba,
         borough = boro) %>% 
  na.omit(grade) %>% 
  mutate(score = as.numeric(score),
         borough = str_to_title(borough)) %>%
  select(camis, year, month, day, borough, name, cuisine_description, score, grade, 
         violation_description) %>% 
  filter(year == "2016",
         score > "0") %>% 
sample_n(20000)
##final dataset
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough = nyc_inspections %>% distinct(borough) %>% pull()

# selectInput widget
selectInput("borough", label = h3("Select borough"),
            choices = borough, selected = "Bronx")

  
grade = nyc_inspections %>% distinct(grade) %>% pull()

# radioButtons widget
radioButtons("grade", label = h3("Choose grade"),
    choices = grade, 
    selected = "A")
```


Row
-----------------------------------------------------------------------

### Chart A

```{r boxplot}
renderPlotly({
    
nyc_inspections %>% 
  filter(grade == input$grade,
         borough == input$borough) %>% 
  unique() %>% 
  mutate(borough = fct_reorder(borough, score)) %>% 
  group_by(borough, name) %>% 
  plot_ly(y = ~score, color = ~borough, type = "box",
          colors = "Set2")
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r scatterplot}
renderPlotly({
nyc_inspections %>% 
  filter(cuisine_description %in% c("Chicken", "Hamburgers", "Vegetarian"),
        grade == input$grade,
        borough == input$borough  ) %>%
  unique() %>% 
  group_by(month, cuisine_description) %>% 
  summarize(mean_score = mean(score)) %>% 
  plot_ly(x = ~month, y = ~mean_score, color = ~cuisine_description, type = "scatter") 
})
```

### Chart C

```{r barplot}
renderPlotly({ 
##addtl dataset for josie
top_cuisines = nyc_inspections %>%
  count(cuisine_description, sort = TRUE) %>% 
  top_n(8) %>% 
  select(cuisine_description) 


nyc_inspections %>% 
  filter(grade == input$grade,
         borough == input$borough) %>% 
  filter(str_detect(violation_description, regex("mice", ignore_case = TRUE)) |
           str_detect(violation_description, regex("flies", ignore_case = TRUE))
         | str_detect(violation_description, regex("roach", ignore_case =
                                                     TRUE))) %>%
  inner_join(top_cuisines, by = "cuisine_description") %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  mutate(cuisine_description = fct_infreq(cuisine_description)) %>%
  group_by(cuisine_description, grade) %>%
  summarize(mean_score = mean(score)) %>%
  plot_ly(x = ~cuisine_description, y = ~mean_score, color = ~grade, type = "bar")
})

```

